language: R
cache: packages

pandoc_version: 2.3.1

# script: Rscript -e 'rmarkdown::render_site()'
script: 
  - Rscript -e 'rmarkdown::render_site()'
  - Rscript -e 'rmarkdown::render_site(input = "curriculum_vitae.Rmd", output_format = "pagedown::html_resume")'

after_success: curl --user ${FTP_USER}:${FTP_PASSWORD} -T _site/curriculum_vitae.html ftp://${FTP_URL}/www/index.html

deploy:
  provider: script
  script: Rscript -e 'source("R/deploy.R"); deploy_site_github()'
  skip_cleanup: true
