language: R
cache: packages

pandoc_version: 2.3.1

before_install:
  - sudo add-apt-repository --yes ppa:cran/imagemagick
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libmagick++-dev

script: 
  - Rscript -e 'rmarkdown::render(input = "curriculum_vitae.Rmd")'

after_success: curl --max-time 10 --retry 4 --user ${FTP_USER}:${FTP_PASSWORD} -T curriculum_vitae.html ftp://${FTP_URL}/www/index.html

before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'

deploy:
  provider: script
  script: Rscript -e 'source("utils/deploy.R"); deploy_site(commit_message = "curriculum_vitae")'
  skip_cleanup: true
