os: linux
dist: xenial
language: r
cache: packages

pandoc_version: 2.3.1

before_install:
  - sudo add-apt-repository --yes ppa:cran/imagemagick
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libmagick++-dev

script: 
  - Rscript -e 'rmarkdown::render(input = "curriculum_vitae.Rmd", output_file = "index.html", encoding = "UTF-8", output_dir = "docs")'

deploy:
  provider: script
  script: cd docs && curl --fail --silent --max-time 10 --retry 4 --user ${FTP_USER}:${FTP_PASSWORD} --upload-file index.html ftp://${FTP_URL}/www/index.html

notifications:
  email:
    on_success: never
    on_failure: never
