language: R
cache: packages

pandoc_version: 2.3.1

script: Rscript -e 'rmarkdown::render_site()'

deploy:
  provider: script
  script: bash _deploy.sh $FTP_USER $FTP_PASSWORD $FTP_URL
  skip_cleanup: true

notifications:
  email:
    on_success: change
    on_failure: change
