language: R
cache: packages

pandoc_version: 2.3.1

before_install:
  - sudo add-apt-repository --yes ppa:cran/imagemagick
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libmagick++-dev

script: 
  - Rscript -e 'rmarkdown::render(input = "curriculum_vitae.Rmd")'

deploy:
  provider: script
  script: curl --max-time 10 --retry 4 --user ${FTP_USER}:${FTP_PASSWORD} -T curriculum_vitae.html ftp://${FTP_URL}/www/index.html
  skip_cleanup: true

notifications:
  email:
    on_success: change
    on_failure: change
