language: R
cache: packages

pandoc_version: 2.3.1

# script: Rscript -e 'rmarkdown::render_site()'
script: 
  - Rscript -e 'rmarkdown::render_site()'
  - Rscript -e 'rmarkdown::render(input = "curriculum_vitae.Rmd", output_format = "pagedown::html_resume")'

after_success: curl --max-time 30 --retry 3 --user ${FTP_USER}:${FTP_PASSWORD} -T _site/curriculum_vitae.html ftp://${FTP_URL}/www/index.html

before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'

deploy:
  provider: script
  script: Rscript -e 'source("R/deploy.R"); deploy_site()'
  skip_cleanup: true
