on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: render-cv

jobs:
  render-cv:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-16.04, r: '4.0', cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          sudo add-apt-repository --yes ppa:cran/imagemagick
          sudo apt-get --yes --force-yes update -qq
          sudo apt-get install --yes libmagick++-dev
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
          
      - name: Install xkcd
        if: runner.os != 'Windows'
        run: |
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Render ANALYSIS
        run: |
          Rscript -e 'rmarkdown::render("curriculum_vitae.Rmd", output_file = "index.html", output_dir = "docs")'
          git config --global user.name "${{secrets.NAME}}"
          git config --global user.email ${{secrets.EMAIL}}
          git commit -am 'update CV' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
          cd docs && curl --fail --silent --max-time 10 --retry 4 --user ${secrets.FTP_USER}:${secrets.FTP_PASSWORD} --upload-file index.html ftp://${secrets.FTP_URL}/www/index.html

